### DISCUSSION TITLE
About .nvmrc

### DISCUSSION THREAD

**Discussion by berkaykrc** [AntonioMrtz/SpotifyElectron#339] [Ideas]
So I was looking your last commit about #337 then I noticed you are replacing node versions by hand on CI more specific
```yaml
 - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
```
Every time you update it to a newer version, you will change the version many places like this but, as I recommended previously, putting .nvmrc file to top folder directory you can just give that file into your .ymal file 

```yml

- uses: actions/setup-node@v4
  with:
    # Version Spec of the version to use in SemVer notation.
    # It also admits such aliases as lts/*, latest, nightly and canary builds
    # Examples: 12.x, 10.15.1, >=10.15.0, lts/Hydrogen, 16-nightly, latest, node
    node-version: ''

    # File containing the version Spec of the version to use.  Examples: package.json, .nvmrc, .node-version, .tool-versions.
    # If node-version and node-version-file are both provided the action will use version from node-version. 
    node-version-file: ''

```
You would eliminate handling versioning in different places, instead you could just write your preferred version in `.nvmrc` and let it take care of the rest. As I stated previously it works for good both CI and programmers.

> Automated Version Management:
   >>.nvmrc automatically switches Node.js versions when developers enter the project directory
    >>Prevents human error from manually switching versions
    >>Works with CI/CD pipelines that support nvm

> I think it should be in SpotifyElectron the project root directory, so any from child folder can pick up from the parent rather than Electron. pre-commit hook prettier also use npm what I understood. I do not know what else depend on it.
>>It affects the entire project, including both frontend and backend
>>Most tools and CI/CD pipelines look for .nvmrc in the root directory by default
>>It ensures consistent Node.js version across all parts of your application

- https://github.com/actions/setup-node?tab=readme-ov-file#usage
- https://github.com/AntonioMrtz/SpotifyElectron/commit/5931fb063114cc16b64f3cf6d3909a87266b32dd
- https://github.com/AntonioMrtz/SpotifyElectron/pull/331#discussion_r19564033247
- https://github.com/AntonioMrtz/SpotifyElectron/pull/331#discussion_r1957362915
