### ISSUE TITLE
Add license to MkDocs

### ISSUE THREAD

**Issue by AntonioMrtz** [AntonioMrtz/SpotifyElectron#297]
## Description

Add copyright to MkDocs 

## Context

Copyright of the project was not shown on MkDocs

## How to do it

Fill the field `copyright` on `mkdocs.yml` with our license. Docs can be found [here](https://www.mkdocs.org/user-guide/configuration/)

```yml
extra:
    copyright: |
      © 2025 [Antonio Martinez]. Licensed under a
      [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-nc-sa/4.0/).
```

## Testing

* Check license is shown using `mkdocs serve` in a local environment

---
__🖐️ Learn [how to CONTRIBUTE](https://antoniomrtz.github.io/SpotifyElectron_Web/docs/CONTRIBUTING/), all help is welcomed :)__

__📚 Check out the [project documentation](https://antoniomrtz.github.io/SpotifyElectron_Web/docs/) for more info__

__⭐ Help this project grow by giving it a star if you like it!__

__😵 Trello links are used for traceability, do not ask to join the board before leaving a comment in the related issue__
