### ISSUE TITLE
Pre-commit pipeline

### ISSUE THREAD

**Issue by AntonioMrtz** [AntonioMrtz/SpotifyElectron#361]
## Description

Implement a Github Actions pipeline that runs specific pre-commit hooks

## Context

There are useful hooks that could improve code quality checks by running in pipeline such as:
- check-yaml
- check-json
- end-of-file-fixer
- trailing-whitespace
- check-merge-conflict

## How to do it

* Create a github action that runs on pushes to a PR (Similar to ruff lint check pipeline).
* Make the pipeline run `pre-commit run <hook_id_1> <hook_id_2> --all-files` with the list of hooks provided in context
* Include a comment in pre-commit config yml telling to update ci pipeline if those hooks change 

## Testing

- Make sure pipeline runs correctly

---

__🖐️ Learn [how to CONTRIBUTE](https://antoniomrtz.github.io/SpotifyElectron_Web/docs/CONTRIBUTING/), all help is welcomed :)__

__📚 Check out the [project documentation](https://antoniomrtz.github.io/SpotifyElectron_Web/docs/) for more info__

__⭐ Help this project grow by giving it a star if you like it!__

__😵 Trello links are used for traceability, do not ask to join the board before leaving a comment in the related issue__

**Comment by AntonioMrtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Pre-commit pipeline for ci hooks](https://trello.com/c/xrCiBvj2/659-pre-commit-pipeline-for-ci-hooks)

**Comment by monokatarina** [comment]
Hey there! 👋

I'd love to help implement this GitHub Actions pipeline for pre-commit hooks. Before I start:

Should these hooks run on every push to any branch, or just PRs?

For the comment in .pre-commit-config.yaml, would something like this work?

Would you like me to include installation/setup of pre-commit in the workflow too?

I'll wait for your guidance before proceeding. This seems like a great improvement!

**Comment by AntonioMrtz** [comment]
Hi @monokatarina 😊 Nice to meet you! I will assign you this issue -- Feel free to ask anything.

* It should run on every push to a branch that has `master-*` target. The trigger should be the same as the one in `ruff-check-lint.yml`
* The comment on `.pre-commit-config.yaml` should be something like this:

```yml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      # Consider updating pre-commit pipeline if a new hook is added
      - id: check-yaml
      - id: check-json
        exclude: ^(.devcontainer/|Electron/.vscode/|Backend/.vscode)
      - id: end-of-file-fixer
        exclude: ^Electron/src/swagger/
      - id: trailing-whitespace
      - id: check-merge-conflict
...
```
* The workflow should have the setup to run `pre-commit` ofc. Install only the required hook ids. Maybe grouping the hook ids into a list and re-use it install and run commands.
