### ISSUE TITLE
Gitleaks pre-commit

### ISSUE THREAD

**Issue by AntonioMrtz** [AntonioMrtz/SpotifyElectron#362]
## Description

Add [gitleaks precommit hook](https://github.com/gitleaks/gitleaks)

## Context

Decrease chance of pushing secrets into the repository

## How to do it

* Add `gitleaks` pre-commit to config file

```
repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks
```

## Testing

* Check pre-commit hook is run in local running `pre-commit run --all-files`

---

__🖐️ Learn [how to CONTRIBUTE](https://antoniomrtz.github.io/SpotifyElectron_Web/docs/CONTRIBUTING/), all help is welcomed :)__

__📚 Check out the [project documentation](https://antoniomrtz.github.io/SpotifyElectron_Web/docs/) for more info__

__⭐ Help this project grow by giving it a star if you like it!__

__😵 Trello links are used for traceability, do not ask to join the board before leaving a comment in the related issue__
